version: '3.9'
services:
  go-app:
    container_name: "go-app"
    build: .
    environment:
      DATABASE_URL: "host=go_db user=zmey56 password=zmey56 dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: zmey56
      POSTGRES_USER: zmey56
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

